apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-push-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: repo-push-dep
      eventSourceName: github-events
      eventName: repo-push
  triggers:
    - template:
        name: kaniko-build-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          namespace: argo-events
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: kaniko-build-
              spec:
                workflowTemplateRef:
                  name: kaniko-build-template
                arguments:
                  parameters:
                    - name: registry-username
                      value: ""
                    - name: image-name
                      value: ""
          parameters:
            - src:
                dependencyName: repo-push-dep
                dataKey: body.repository.owner.name
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: repo-push-dep
                dataKey: body.repository.name
              dest: spec.arguments.parameters.1.value
