apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaniko-workspace
  namespace: argo-events
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
