apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflow-template-access
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtemplates", "workflows"]
    verbs: ["get", "list", "create", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-template-access-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: argo-events
roleRef:
  kind: ClusterRole
  name: argo-workflow-template-access
  apiGroup: rbac.authorization.k8s.io
